/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ClientCasesRouteImport } from './routes/client-cases'
import { Route as ClientDashboardRouteImport } from './routes/client-dashboard'
import { Route as ClientDocumentsRouteImport } from './routes/client-documents'
import { Route as ClientHearingsRouteImport } from './routes/client-hearings'
import { Route as ClientInvoicesRouteImport } from './routes/client-invoices'
import { Route as ClientMessagesRouteImport } from './routes/client-messages'
import { Route as ClientProfileRouteImport } from './routes/client-profile'
import { Route as ClientSupportRouteImport } from './routes/client-support'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FirmsRouteImport } from './routes/firms'
import { Route as LawyerCasesRouteImport } from './routes/lawyer-cases'
import { Route as LawyerCasesNewRouteImport } from './routes/lawyer-cases-new'
import { Route as LawyerClientsRouteImport } from './routes/lawyer-clients'
import { Route as LawyerClientsNewRouteImport } from './routes/lawyer-clients-new'
import { Route as LawyerDashboardRouteImport } from './routes/lawyer-dashboard'
import { Route as LawyerDocumentsRouteImport } from './routes/lawyer-documents'
import { Route as LawyerHearingsRouteImport } from './routes/lawyer-hearings'
import { Route as LawyerInvoicesRouteImport } from './routes/lawyer-invoices'
import { Route as LawyerNotificationsRouteImport } from './routes/lawyer-notifications'
import { Route as LawyerReportsRouteImport } from './routes/lawyer-reports'
import { Route as LawyerSettingsRouteImport } from './routes/lawyer-settings'
import { Route as LawyerTeamRouteImport } from './routes/lawyer-team'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ClientCaseDetailCaseIdRouteImport } from './routes/client-case-detail.$caseId'
import { Route as FirmDetailFirmIdRouteImport } from './routes/firm-detail.$firmId'
import { Route as FirmsFirmIdRouteImport } from './routes/firms.$firmId'
import { Route as LawyerCaseDetailCaseIdRouteImport } from './routes/lawyer-case-detail.$caseId'
import { Route as LawyerClientDetailClientIdRouteImport } from './routes/lawyer-client-detail.$clientId'
import { Route as TicketDetailTicketIdRouteImport } from './routes/ticket-detail.$ticketId'
import { Route as UserDetailUserIdRouteImport } from './routes/user-detail.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCasesRoute = ClientCasesRouteImport.update({
  id: '/client-cases',
  path: '/client-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client-dashboard',
  path: '/client-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/client-documents',
  path: '/client-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHearingsRoute = ClientHearingsRouteImport.update({
  id: '/client-hearings',
  path: '/client-hearings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/client-invoices',
  path: '/client-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/client-messages',
  path: '/client-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client-profile',
  path: '/client-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/client-support',
  path: '/client-support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsRoute = FirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerCasesRoute = LawyerCasesRouteImport.update({
  id: '/lawyer-cases',
  path: '/lawyer-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerCasesNewRoute = LawyerCasesNewRouteImport.update({
  id: '/lawyer-cases-new',
  path: '/lawyer-cases-new',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerClientsRoute = LawyerClientsRouteImport.update({
  id: '/lawyer-clients',
  path: '/lawyer-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerClientsNewRoute = LawyerClientsNewRouteImport.update({
  id: '/lawyer-clients-new',
  path: '/lawyer-clients-new',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerDashboardRoute = LawyerDashboardRouteImport.update({
  id: '/lawyer-dashboard',
  path: '/lawyer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerDocumentsRoute = LawyerDocumentsRouteImport.update({
  id: '/lawyer-documents',
  path: '/lawyer-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerHearingsRoute = LawyerHearingsRouteImport.update({
  id: '/lawyer-hearings',
  path: '/lawyer-hearings',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerInvoicesRoute = LawyerInvoicesRouteImport.update({
  id: '/lawyer-invoices',
  path: '/lawyer-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerNotificationsRoute = LawyerNotificationsRouteImport.update({
  id: '/lawyer-notifications',
  path: '/lawyer-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerReportsRoute = LawyerReportsRouteImport.update({
  id: '/lawyer-reports',
  path: '/lawyer-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerSettingsRoute = LawyerSettingsRouteImport.update({
  id: '/lawyer-settings',
  path: '/lawyer-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerTeamRoute = LawyerTeamRouteImport.update({
  id: '/lawyer-team',
  path: '/lawyer-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCaseDetailCaseIdRoute = ClientCaseDetailCaseIdRouteImport.update({
  id: '/client-case-detail/$caseId',
  path: '/client-case-detail/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmDetailFirmIdRoute = FirmDetailFirmIdRouteImport.update({
  id: '/firm-detail/$firmId',
  path: '/firm-detail/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsFirmIdRoute = FirmsFirmIdRouteImport.update({
  id: '/$firmId',
  path: '/$firmId',
  getParentRoute: () => FirmsRoute,
} as any)
const LawyerCaseDetailCaseIdRoute = LawyerCaseDetailCaseIdRouteImport.update({
  id: '/lawyer-case-detail/$caseId',
  path: '/lawyer-case-detail/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerClientDetailClientIdRoute =
  LawyerClientDetailClientIdRouteImport.update({
    id: '/lawyer-client-detail/$clientId',
    path: '/lawyer-client-detail/$clientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TicketDetailTicketIdRoute = TicketDetailTicketIdRouteImport.update({
  id: '/ticket-detail/$ticketId',
  path: '/ticket-detail/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDetailUserIdRoute = UserDetailUserIdRouteImport.update({
  id: '/user-detail/$userId',
  path: '/user-detail/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/client-cases': typeof ClientCasesRoute
  '/client-dashboard': typeof ClientDashboardRoute
  '/client-documents': typeof ClientDocumentsRoute
  '/client-hearings': typeof ClientHearingsRoute
  '/client-invoices': typeof ClientInvoicesRoute
  '/client-messages': typeof ClientMessagesRoute
  '/client-profile': typeof ClientProfileRoute
  '/client-support': typeof ClientSupportRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/lawyer-cases': typeof LawyerCasesRoute
  '/lawyer-cases-new': typeof LawyerCasesNewRoute
  '/lawyer-clients': typeof LawyerClientsRoute
  '/lawyer-clients-new': typeof LawyerClientsNewRoute
  '/lawyer-dashboard': typeof LawyerDashboardRoute
  '/lawyer-documents': typeof LawyerDocumentsRoute
  '/lawyer-hearings': typeof LawyerHearingsRoute
  '/lawyer-invoices': typeof LawyerInvoicesRoute
  '/lawyer-notifications': typeof LawyerNotificationsRoute
  '/lawyer-reports': typeof LawyerReportsRoute
  '/lawyer-settings': typeof LawyerSettingsRoute
  '/lawyer-team': typeof LawyerTeamRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/client-case-detail/$caseId': typeof ClientCaseDetailCaseIdRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyer-case-detail/$caseId': typeof LawyerCaseDetailCaseIdRoute
  '/lawyer-client-detail/$clientId': typeof LawyerClientDetailClientIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/client-cases': typeof ClientCasesRoute
  '/client-dashboard': typeof ClientDashboardRoute
  '/client-documents': typeof ClientDocumentsRoute
  '/client-hearings': typeof ClientHearingsRoute
  '/client-invoices': typeof ClientInvoicesRoute
  '/client-messages': typeof ClientMessagesRoute
  '/client-profile': typeof ClientProfileRoute
  '/client-support': typeof ClientSupportRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/lawyer-cases': typeof LawyerCasesRoute
  '/lawyer-cases-new': typeof LawyerCasesNewRoute
  '/lawyer-clients': typeof LawyerClientsRoute
  '/lawyer-clients-new': typeof LawyerClientsNewRoute
  '/lawyer-dashboard': typeof LawyerDashboardRoute
  '/lawyer-documents': typeof LawyerDocumentsRoute
  '/lawyer-hearings': typeof LawyerHearingsRoute
  '/lawyer-invoices': typeof LawyerInvoicesRoute
  '/lawyer-notifications': typeof LawyerNotificationsRoute
  '/lawyer-reports': typeof LawyerReportsRoute
  '/lawyer-settings': typeof LawyerSettingsRoute
  '/lawyer-team': typeof LawyerTeamRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/client-case-detail/$caseId': typeof ClientCaseDetailCaseIdRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyer-case-detail/$caseId': typeof LawyerCaseDetailCaseIdRoute
  '/lawyer-client-detail/$clientId': typeof LawyerClientDetailClientIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/client-cases': typeof ClientCasesRoute
  '/client-dashboard': typeof ClientDashboardRoute
  '/client-documents': typeof ClientDocumentsRoute
  '/client-hearings': typeof ClientHearingsRoute
  '/client-invoices': typeof ClientInvoicesRoute
  '/client-messages': typeof ClientMessagesRoute
  '/client-profile': typeof ClientProfileRoute
  '/client-support': typeof ClientSupportRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/lawyer-cases': typeof LawyerCasesRoute
  '/lawyer-cases-new': typeof LawyerCasesNewRoute
  '/lawyer-clients': typeof LawyerClientsRoute
  '/lawyer-clients-new': typeof LawyerClientsNewRoute
  '/lawyer-dashboard': typeof LawyerDashboardRoute
  '/lawyer-documents': typeof LawyerDocumentsRoute
  '/lawyer-hearings': typeof LawyerHearingsRoute
  '/lawyer-invoices': typeof LawyerInvoicesRoute
  '/lawyer-notifications': typeof LawyerNotificationsRoute
  '/lawyer-reports': typeof LawyerReportsRoute
  '/lawyer-settings': typeof LawyerSettingsRoute
  '/lawyer-team': typeof LawyerTeamRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/client-case-detail/$caseId': typeof ClientCaseDetailCaseIdRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyer-case-detail/$caseId': typeof LawyerCaseDetailCaseIdRoute
  '/lawyer-client-detail/$clientId': typeof LawyerClientDetailClientIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/client-cases'
    | '/client-dashboard'
    | '/client-documents'
    | '/client-hearings'
    | '/client-invoices'
    | '/client-messages'
    | '/client-profile'
    | '/client-support'
    | '/dashboard'
    | '/firms'
    | '/lawyer-cases'
    | '/lawyer-cases-new'
    | '/lawyer-clients'
    | '/lawyer-clients-new'
    | '/lawyer-dashboard'
    | '/lawyer-documents'
    | '/lawyer-hearings'
    | '/lawyer-invoices'
    | '/lawyer-notifications'
    | '/lawyer-reports'
    | '/lawyer-settings'
    | '/lawyer-team'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/client-case-detail/$caseId'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/lawyer-case-detail/$caseId'
    | '/lawyer-client-detail/$clientId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/client-cases'
    | '/client-dashboard'
    | '/client-documents'
    | '/client-hearings'
    | '/client-invoices'
    | '/client-messages'
    | '/client-profile'
    | '/client-support'
    | '/dashboard'
    | '/firms'
    | '/lawyer-cases'
    | '/lawyer-cases-new'
    | '/lawyer-clients'
    | '/lawyer-clients-new'
    | '/lawyer-dashboard'
    | '/lawyer-documents'
    | '/lawyer-hearings'
    | '/lawyer-invoices'
    | '/lawyer-notifications'
    | '/lawyer-reports'
    | '/lawyer-settings'
    | '/lawyer-team'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/client-case-detail/$caseId'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/lawyer-case-detail/$caseId'
    | '/lawyer-client-detail/$clientId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/client-cases'
    | '/client-dashboard'
    | '/client-documents'
    | '/client-hearings'
    | '/client-invoices'
    | '/client-messages'
    | '/client-profile'
    | '/client-support'
    | '/dashboard'
    | '/firms'
    | '/lawyer-cases'
    | '/lawyer-cases-new'
    | '/lawyer-clients'
    | '/lawyer-clients-new'
    | '/lawyer-dashboard'
    | '/lawyer-documents'
    | '/lawyer-hearings'
    | '/lawyer-invoices'
    | '/lawyer-notifications'
    | '/lawyer-reports'
    | '/lawyer-settings'
    | '/lawyer-team'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/client-case-detail/$caseId'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/lawyer-case-detail/$caseId'
    | '/lawyer-client-detail/$clientId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  ClientCasesRoute: typeof ClientCasesRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientHearingsRoute: typeof ClientHearingsRoute
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientSupportRoute: typeof ClientSupportRoute
  DashboardRoute: typeof DashboardRoute
  FirmsRoute: typeof FirmsRouteWithChildren
  LawyerCasesRoute: typeof LawyerCasesRoute
  LawyerCasesNewRoute: typeof LawyerCasesNewRoute
  LawyerClientsRoute: typeof LawyerClientsRoute
  LawyerClientsNewRoute: typeof LawyerClientsNewRoute
  LawyerDashboardRoute: typeof LawyerDashboardRoute
  LawyerDocumentsRoute: typeof LawyerDocumentsRoute
  LawyerHearingsRoute: typeof LawyerHearingsRoute
  LawyerInvoicesRoute: typeof LawyerInvoicesRoute
  LawyerNotificationsRoute: typeof LawyerNotificationsRoute
  LawyerReportsRoute: typeof LawyerReportsRoute
  LawyerSettingsRoute: typeof LawyerSettingsRoute
  LawyerTeamRoute: typeof LawyerTeamRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TicketsRoute: typeof TicketsRoute
  UsersRoute: typeof UsersRoute
  ClientCaseDetailCaseIdRoute: typeof ClientCaseDetailCaseIdRoute
  FirmDetailFirmIdRoute: typeof FirmDetailFirmIdRoute
  LawyerCaseDetailCaseIdRoute: typeof LawyerCaseDetailCaseIdRoute
  LawyerClientDetailClientIdRoute: typeof LawyerClientDetailClientIdRoute
  TicketDetailTicketIdRoute: typeof TicketDetailTicketIdRoute
  UserDetailUserIdRoute: typeof UserDetailUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-cases': {
      id: '/client-cases'
      path: '/client-cases'
      fullPath: '/client-cases'
      preLoaderRoute: typeof ClientCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-dashboard': {
      id: '/client-dashboard'
      path: '/client-dashboard'
      fullPath: '/client-dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-documents': {
      id: '/client-documents'
      path: '/client-documents'
      fullPath: '/client-documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-hearings': {
      id: '/client-hearings'
      path: '/client-hearings'
      fullPath: '/client-hearings'
      preLoaderRoute: typeof ClientHearingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-invoices': {
      id: '/client-invoices'
      path: '/client-invoices'
      fullPath: '/client-invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-messages': {
      id: '/client-messages'
      path: '/client-messages'
      fullPath: '/client-messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-profile': {
      id: '/client-profile'
      path: '/client-profile'
      fullPath: '/client-profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-support': {
      id: '/client-support'
      path: '/client-support'
      fullPath: '/client-support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms': {
      id: '/firms'
      path: '/firms'
      fullPath: '/firms'
      preLoaderRoute: typeof FirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-cases': {
      id: '/lawyer-cases'
      path: '/lawyer-cases'
      fullPath: '/lawyer-cases'
      preLoaderRoute: typeof LawyerCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-cases-new': {
      id: '/lawyer-cases-new'
      path: '/lawyer-cases-new'
      fullPath: '/lawyer-cases-new'
      preLoaderRoute: typeof LawyerCasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-clients': {
      id: '/lawyer-clients'
      path: '/lawyer-clients'
      fullPath: '/lawyer-clients'
      preLoaderRoute: typeof LawyerClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-clients-new': {
      id: '/lawyer-clients-new'
      path: '/lawyer-clients-new'
      fullPath: '/lawyer-clients-new'
      preLoaderRoute: typeof LawyerClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-dashboard': {
      id: '/lawyer-dashboard'
      path: '/lawyer-dashboard'
      fullPath: '/lawyer-dashboard'
      preLoaderRoute: typeof LawyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-documents': {
      id: '/lawyer-documents'
      path: '/lawyer-documents'
      fullPath: '/lawyer-documents'
      preLoaderRoute: typeof LawyerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-hearings': {
      id: '/lawyer-hearings'
      path: '/lawyer-hearings'
      fullPath: '/lawyer-hearings'
      preLoaderRoute: typeof LawyerHearingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-invoices': {
      id: '/lawyer-invoices'
      path: '/lawyer-invoices'
      fullPath: '/lawyer-invoices'
      preLoaderRoute: typeof LawyerInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-notifications': {
      id: '/lawyer-notifications'
      path: '/lawyer-notifications'
      fullPath: '/lawyer-notifications'
      preLoaderRoute: typeof LawyerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-reports': {
      id: '/lawyer-reports'
      path: '/lawyer-reports'
      fullPath: '/lawyer-reports'
      preLoaderRoute: typeof LawyerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-settings': {
      id: '/lawyer-settings'
      path: '/lawyer-settings'
      fullPath: '/lawyer-settings'
      preLoaderRoute: typeof LawyerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-team': {
      id: '/lawyer-team'
      path: '/lawyer-team'
      fullPath: '/lawyer-team'
      preLoaderRoute: typeof LawyerTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-case-detail/$caseId': {
      id: '/client-case-detail/$caseId'
      path: '/client-case-detail/$caseId'
      fullPath: '/client-case-detail/$caseId'
      preLoaderRoute: typeof ClientCaseDetailCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm-detail/$firmId': {
      id: '/firm-detail/$firmId'
      path: '/firm-detail/$firmId'
      fullPath: '/firm-detail/$firmId'
      preLoaderRoute: typeof FirmDetailFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/$firmId': {
      id: '/firms/$firmId'
      path: '/$firmId'
      fullPath: '/firms/$firmId'
      preLoaderRoute: typeof FirmsFirmIdRouteImport
      parentRoute: typeof FirmsRoute
    }
    '/lawyer-case-detail/$caseId': {
      id: '/lawyer-case-detail/$caseId'
      path: '/lawyer-case-detail/$caseId'
      fullPath: '/lawyer-case-detail/$caseId'
      preLoaderRoute: typeof LawyerCaseDetailCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-client-detail/$clientId': {
      id: '/lawyer-client-detail/$clientId'
      path: '/lawyer-client-detail/$clientId'
      fullPath: '/lawyer-client-detail/$clientId'
      preLoaderRoute: typeof LawyerClientDetailClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-detail/$ticketId': {
      id: '/ticket-detail/$ticketId'
      path: '/ticket-detail/$ticketId'
      fullPath: '/ticket-detail/$ticketId'
      preLoaderRoute: typeof TicketDetailTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-detail/$userId': {
      id: '/user-detail/$userId'
      path: '/user-detail/$userId'
      fullPath: '/user-detail/$userId'
      preLoaderRoute: typeof UserDetailUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FirmsRouteChildren {
  FirmsFirmIdRoute: typeof FirmsFirmIdRoute
}

const FirmsRouteChildren: FirmsRouteChildren = {
  FirmsFirmIdRoute: FirmsFirmIdRoute,
}

const FirmsRouteWithChildren = FirmsRoute._addFileChildren(FirmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  ClientCasesRoute: ClientCasesRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientHearingsRoute: ClientHearingsRoute,
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientSupportRoute: ClientSupportRoute,
  DashboardRoute: DashboardRoute,
  FirmsRoute: FirmsRouteWithChildren,
  LawyerCasesRoute: LawyerCasesRoute,
  LawyerCasesNewRoute: LawyerCasesNewRoute,
  LawyerClientsRoute: LawyerClientsRoute,
  LawyerClientsNewRoute: LawyerClientsNewRoute,
  LawyerDashboardRoute: LawyerDashboardRoute,
  LawyerDocumentsRoute: LawyerDocumentsRoute,
  LawyerHearingsRoute: LawyerHearingsRoute,
  LawyerInvoicesRoute: LawyerInvoicesRoute,
  LawyerNotificationsRoute: LawyerNotificationsRoute,
  LawyerReportsRoute: LawyerReportsRoute,
  LawyerSettingsRoute: LawyerSettingsRoute,
  LawyerTeamRoute: LawyerTeamRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TicketsRoute: TicketsRoute,
  UsersRoute: UsersRoute,
  ClientCaseDetailCaseIdRoute: ClientCaseDetailCaseIdRoute,
  FirmDetailFirmIdRoute: FirmDetailFirmIdRoute,
  LawyerCaseDetailCaseIdRoute: LawyerCaseDetailCaseIdRoute,
  LawyerClientDetailClientIdRoute: LawyerClientDetailClientIdRoute,
  TicketDetailTicketIdRoute: TicketDetailTicketIdRoute,
  UserDetailUserIdRoute: UserDetailUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
