/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FirmsRouteImport } from './routes/firms'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as UsersRouteImport } from './routes/users'
import { Route as FirmDetailFirmIdRouteImport } from './routes/firm-detail.$firmId'
import { Route as FirmsFirmIdRouteImport } from './routes/firms.$firmId'
import { Route as TicketDetailTicketIdRouteImport } from './routes/ticket-detail.$ticketId'
import { Route as UserDetailUserIdRouteImport } from './routes/user-detail.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsRoute = FirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmDetailFirmIdRoute = FirmDetailFirmIdRouteImport.update({
  id: '/firm-detail/$firmId',
  path: '/firm-detail/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsFirmIdRoute = FirmsFirmIdRouteImport.update({
  id: '/$firmId',
  path: '/$firmId',
  getParentRoute: () => FirmsRoute,
} as any)
const TicketDetailTicketIdRoute = TicketDetailTicketIdRouteImport.update({
  id: '/ticket-detail/$ticketId',
  path: '/ticket-detail/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDetailUserIdRoute = UserDetailUserIdRouteImport.update({
  id: '/user-detail/$userId',
  path: '/user-detail/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/firms': typeof FirmsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/firm-detail/$firmId': typeof FirmDetailFirmIdRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/ticket-detail/$ticketId': typeof TicketDetailTicketIdRoute
  '/user-detail/$userId': typeof UserDetailUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/dashboard'
    | '/firms'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/dashboard'
    | '/firms'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/dashboard'
    | '/firms'
    | '/reports'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/subscriptions'
    | '/tickets'
    | '/users'
    | '/firm-detail/$firmId'
    | '/firms/$firmId'
    | '/ticket-detail/$ticketId'
    | '/user-detail/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  FirmsRoute: typeof FirmsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TicketsRoute: typeof TicketsRoute
  UsersRoute: typeof UsersRoute
  FirmDetailFirmIdRoute: typeof FirmDetailFirmIdRoute
  TicketDetailTicketIdRoute: typeof TicketDetailTicketIdRoute
  UserDetailUserIdRoute: typeof UserDetailUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms': {
      id: '/firms'
      path: '/firms'
      fullPath: '/firms'
      preLoaderRoute: typeof FirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm-detail/$firmId': {
      id: '/firm-detail/$firmId'
      path: '/firm-detail/$firmId'
      fullPath: '/firm-detail/$firmId'
      preLoaderRoute: typeof FirmDetailFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/$firmId': {
      id: '/firms/$firmId'
      path: '/$firmId'
      fullPath: '/firms/$firmId'
      preLoaderRoute: typeof FirmsFirmIdRouteImport
      parentRoute: typeof FirmsRoute
    }
    '/ticket-detail/$ticketId': {
      id: '/ticket-detail/$ticketId'
      path: '/ticket-detail/$ticketId'
      fullPath: '/ticket-detail/$ticketId'
      preLoaderRoute: typeof TicketDetailTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-detail/$userId': {
      id: '/user-detail/$userId'
      path: '/user-detail/$userId'
      fullPath: '/user-detail/$userId'
      preLoaderRoute: typeof UserDetailUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FirmsRouteChildren {
  FirmsFirmIdRoute: typeof FirmsFirmIdRoute
}

const FirmsRouteChildren: FirmsRouteChildren = {
  FirmsFirmIdRoute: FirmsFirmIdRoute,
}

const FirmsRouteWithChildren = FirmsRoute._addFileChildren(FirmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  FirmsRoute: FirmsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TicketsRoute: TicketsRoute,
  UsersRoute: UsersRoute,
  FirmDetailFirmIdRoute: FirmDetailFirmIdRoute,
  TicketDetailTicketIdRoute: TicketDetailTicketIdRoute,
  UserDetailUserIdRoute: UserDetailUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
